source 'https://rubygems.org'

gem 'redis'
gem 'em-websocket'
gem 'parse_p1', :git => 'git://github.com/enix/ParseP1.git'
gem 'serialport'
gem 'active_support'
gem 'time_difference'
gem 'eventmachine'
gem 'trollop'
gem 'i2c'

group :development, :test do
	gem 'rspec'
end
