source 'https://rubygems.org'

gem 'sinatra', :require => 'sinatra/base'
gem 'rack-flash3', :require => 'rack-flash'
gem 'redis'
gem 'therubyracer'
gem 'activesupport'
gem 'time_difference'
gem 'em-websocket'