source 'https://rubygems.org'

gem 'sinatra', :require => 'sinatra/base'
gem 'rack-flash3', :require => 'rack-flash'
gem 'redis'
gem 'activesupport'
gem 'time_difference'
gem 'em-websocket'

group :development, :test do
	gem 'rack-test'
	gem 'less'
	gem 'therubyracer'
	gem 'rspec'
end